include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: true
    - prefer_single_quotes: true
    - sort_child_properties_last: true
    - use_key_in_widget_constructors: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore 