name: food_scanner
description: A Flutter app for scanning food ingredients and analyzing their health impact.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_barcode_scanner: ^2.0.0
  http: ^1.1.0
  provider: ^6.0.5
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 